### ISSUE TITLE
CircularProgress breaks when start and end points are set

### ISSUE THREAD

**Issue by Strix-Vyxlor** [Aylur/astal#279]
**Describe the bug**
While trying to use CircularProgress for cpu usage, it broke
by rendering past the end point: with a value of .1 (it stops at .3).

![Image](https://github.com/user-attachments/assets/a1e2f4b9-49f4-4d2c-877c-ec00adcf23b6)

a value of 1:

![Image](https://github.com/user-attachments/assets/8054072a-b7c2-46c1-9344-7d4442b4f10a)

a value of .5:

![Image](https://github.com/user-attachments/assets/0f2d56b8-7694-4b4a-b934-67c718393308)

**To Reproduce**
Create a window with a CircularProgress set startAt (130/360) and EndAt (50/360). than change value to under .2.

example code (what i used):
app.ts
```typescript
import { App } from "astal/gtk3"
import style from "./style.scss"
import Test from "./widget/Test"

App.start({
  css: style,
  main() {
    Test()
  },
})
```
widget/Test.tsx
```typescript
import { Astal, Gtk } from "astal/gtk3"

export default function Test() {
  return <window>
    <box>
      <circularprogress startAt={130 / 360} endAt={50 / 360} value={.5}>
        <icon />
      </circularprogress>
    </box>
  </window>
}
``` 
style.scss
```scss
// https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/theme/Adwaita/_colors-public.scss
$fg-color: #{"@theme_fg_color"};
$bg-color: #{"@theme_bg_color"};

window {
  background: $bg-color;
  color: $fg-color;
  font-weight: bold;
    
  box {
    circularprogress {
      font-size: 14px;
      min-width: 200px;
      min-height: 200px;
      background: red;
    }
  }
}
```

**Expected behavior**
progress not overflowing, like the value 1 and .5

**Additional context**
I am on rpi5 with voidlinux musl [packaged here](https://github.com/Strix-Vyxlor/void-packages)
