### ISSUE TITLE
GTK4 and GTK3 backround-color are inconsistent when hover

### ISSUE THREAD

**Issue by The-Lost-Light** [Aylur/astal#310]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [X] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [X] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**

```scss
#power-menu button {
	...
	background-color: #2e3440;
	...
}
```

**Describe your question**

I am trying to migrate to ags-v2. I found that in the gtk3 version, when I set the background-color of a button, it does not affect the hover state (for example, red text will make the hover state button background also a little red). However, when using gtk4, the hover state and non-hover state are completely unchanged. How can I achieve the same visual effect as in gtk3?

No hover:
![Image](https://github.com/user-attachments/assets/0aaeae36-a15e-44e5-b2ff-9ec1acc8c833)

hover(only in gtk3):
![Image](https://github.com/user-attachments/assets/f22e220f-9b8e-4eb2-8433-d87ef659e739)

**Comment by kotontrion** [comment]
You want the `:hover` pseudo class. You can also use the mix function to mix colors together:

```css
#power-menu button:hover {
    background-color: mix(#2e3440, currentColor, 0.3);
}
```

**Comment by The-Lost-Light** [comment]
> You want the `:hover` pseudo class. You can also use the mix function to mix colors together:
> 
> #power-menu button:hover {
>     background-color: mix(#2e3440, currentColor, 0.3);
> }

currentColor seem can't use in mix()

**Comment by The-Lost-Light** [comment]
```scss
#power-menu .background {
	background-color: #2e3440;
	border-radius: 10px;
	margin: 20px;

	button {
		font-size: 48px;
		min-width: 96px;
		min-height: 96px;
		padding: 2px;

		&:not(:hover) {
			background-color: transparent;
		}

		&#poweroff {
			color: palette.$red;
		}
	}
}
```
I finally wrapped the button in a box and changed the background-color of the box and also changed the background-color of the non-hover button to transparent
