### ISSUE TITLE
Scrollable box

### ISSUE THREAD

**Issue by katashisano** [Aylur/astal#337]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**
I tried editing css style of `<scrollable>`, but that does nothing.
I also tried using Gtk.Layout with astalify but I was not able to understand how to use it properly.
Set borderWidth property in js.

**Describe your question**
How can I make a scrollable box with the same style as these other boxes? (third is `<scrollable>`)

![Image](https://github.com/user-attachments/assets/80075bd8-ee85-4043-9521-ef0a51169f22)

**Comment by viceav** [comment]
what is your css rule?
try adding 
```css
scrollable {
   your style
}
```

**Comment by katashisano** [comment]
My style for that is
```css
.wifi-list {
      $f-size: 14px;
      font-size: $f-size;
      margin: .7rem;
      margin-top: 0;
      border-radius: calc(.8rem * 0.35);
      background: $color1;
      .netw {
        >box {
          margin: 1rem;
          margin-top: 0;
          >icon {
            font-size: calc($f-size * 2);
            margin-right: 1rem;
          }
        }
        .connectBut {
          margin: 0;
          margin-top: 1rem;
          margin-bottom: 1rem;
          padding-right: 1rem;
          >button {
            $shadow-color: #222222aa;
            transition: background-color linear 1s;
            box-shadow: 0 3px 3px $shadow-color;
            all: unset;
            padding: .5rem;
            background: lighten($color1, 5%);
            border: 2px solid lighten($color1, 20%);
            border-radius: calc(.8rem * 0.35);
            min-width: 100px;
            &:hover {
              background: lighten($color1, 20%);
            }
          }
        }
      }
      .rescanBut {
        margin: 1rem;
        >button {
          $shadow-color: #222222aa;
          transition: background-color linear 1s;
          box-shadow: 0 3px 3px $shadow-color;
          all: unset;
          padding: .5rem;
          background: lighten($color1, 5%);
          border: 2px solid lighten($color1, 20%);
          border-radius: calc(.8rem * 0.35);
          min-width: 100px;
          &:hover {
            background: lighten($color1, 20%);
          }
        }
      }
      .disconnectWBut {
        @extend .rescanBut;
        margin-left: 0;
      }
      .netw-unav {
        margin: 1rem;
      }
    }
``` 

First box's css is:
```css
.main-net {
      $f-size: 24px;
      font-size: $f-size;
      background: $color1;
      margin: .7rem;
      border-radius: calc(.8rem * 0.35);
      >icon {
        font-size: calc($f-size * 3);
        margin: 1rem;
      }
      >box {
        margin-right: 1rem;
        .net2 {
          font-size: calc($f-size * 0.5);
        }
        >label {
          margin-left: 2em;
        }
      }
    }
```

And my code for the scrollable element is:
```jsx
<scrollable className="wifi-list"
			visible={bind(network.wifi, "enabled")}
			vexpand
			maxContentHeight={800}
			hscroll={Gtk.PolicyType.NEVER}
			heightRequest={800}
			>
			<box vertical vexpand>
				<box>
					//rescan and disconnect buttons code
				</box>
				//access point list code
			</box>
			</scrollable>

```

Both have border-radius and box-shadow set, but wifi-list isn't styled like main-net. I also tried changing ".wifi-list" to "scrollable" in my css, but it stayed the same. Btw, this is how it is looking right now:

![Image](https://github.com/user-attachments/assets/eecd2ff8-a02f-498b-a513-b297c61e9222)

**Comment by viceav** [comment]
@katashisano can u try this please?
```css
viewport {
      border: 3px solid #fff
      border-radius: calc(.8rem * 0.35);
}
```
