### ISSUE TITLE
How to add background transparency with gtk variable color

### ISSUE THREAD

**Issue by permafrozen** [Aylur/astal#90]
## **Have you read through the documentation?**
- [X] [Astal docs](https://aylur.github.io/astal/)
- [X] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [X] [FAQ](https://aylur.github.io/astal/guide/ags/faq)

## **Describe what have you tried so far**
Used my gtk theme color with `scss` functions like e.g. `rgba()`:

```scss
$fg_color: "@window_fg_color";
$bg_color: "@window_bg_color";

window.Bar {
    background: transparent;
    color: #{$bg_color};
    font-weight: bold;

    >centerbox {
        background: rgba(#{$bg_color}, 0.5);
        border-radius: 10px;
        margin: 0px;
    }

    button {
        border-radius: 8px;
        margin: 2px;
    }
}

```

But then I get an error:

```bash
.dot-nixe on  main [!] 
  ags run
Error: $color: @window_bg_color is not a color.
   ╷
10 │         background: rgba(#{$bg_color}, 0.5);
   │                     ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  nix/store/i5rm7f4m09fgnxgf3pv059rvy2jn9i5y-hm_project/style.scss 10:21  root stylesheet
✘ [ERROR] exit status 65 [plugin sass]

    app.ts:2:18:
      2 │ import style from "./style.scss"
        ╵                   ~~~~~~~~~~~~~~
```

But I already tried `window_bg_color` as a normal color like `background: ${$bg_color}` and it works.

## **Describe your question**
I Tried to read a little documentation about this, and I have no idea why this didn't work. If I use a hardcoded value like `#fff` it works, but I really want to use my dynamic generated gtk theme.

Also I love your project, keep going :+1: :100:
